#
#
#
---
#

version: "3.5"
services:
#
  hive-postgresql:
    image: brijeshdhaker/hive-postgresql:2.3.7
    build:
      context: .
      dockerfile: docker-hive-2.3.7/postgres/Dockerfile
    hostname: hive-postgresql
    container_name: hive-postgresql
    ports:
      - "5432:5432"
    volumes:
      - /apps/hostpath:/apps/hostpath

#
  hive-metastore:
    image: brijeshdhaker/hive:2.3.7
    build:
      context: .
      dockerfile: docker-hive-2.3.7/hive/Dockerfile
    hostname: hive-metastore
    container_name: hive-metastore
    env_file:
      - docker-hive-2.3.7/hive-2.3.7.env
    command: /opt/hive-2.3.7/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-postgresql:5432"
    links:
      - hive-postgresql
    ports:
      - "9083:9083"
    volumes:
      - /apps/hostpath:/apps/hostpath

#
  hive-server:
    image: brijeshdhaker/hive:2.3.7
    hostname: hive-server
    container_name: hive-server
    env_file:
      - docker-hive-2.3.7/hive-2.3.7.env
    links:
      - hive-metastore  
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-postgresql/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - /apps/hostpath:/apps/hostpath
      - /opt/hbase-1.1.1:/opt/hbase-1.1.1

#
volumes:
  namenode:
  datanode:

#
networks:
  default:
    external: true
    driver: bridge
    name: bigdata.net