version: "3.5"

services:

  #
  namenode:
    image: brijeshdhaker/hadoop-namenode:2.7.4
    build:
      context: .
      dockerfile: docker-hadoop-2.7.4/namenode/Dockerfile
    container_name: namenode
    hostname: namenode
    restart: always
    extra_hosts:
      - "thinkpad thinkpad.bigdata.net:host-gateway"
    ports:
      - "50070:50070"
      - "9000:9000"
    volumes:
      - /apps/hostpath:/apps/hostpath
    environment:
      - CLUSTER_NAME=test
    env_file:
      - docker-hadoop-2.7.4/hadoop-2.7.4.env

  #
  datanode:
    image: brijeshdhaker/hadoop-datanode:2.7.4
    build:
      context: .
      dockerfile: docker-hadoop-2.7.4/datanode/Dockerfile
    container_name: datanode
    hostname: datanode
    extra_hosts:
      - "thinkpad thinkpad.bigdata.net:host-gateway"
    ports:
      - "50075:50075"
      - "50010:50010"
    restart: always
    volumes:
      - /apps/hostpath:/apps/hostpath
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - docker-hadoop-2.7.4/hadoop-2.7.4.env

  #
  resourcemanager:
    image: brijeshdhaker/hadoop-resourcemanager:2.7.4
    build:
      context: .
      dockerfile: docker-hadoop-2.7.4/resourcemanager/Dockerfile
    container_name: resourcemanager
    hostname: resourcemanager
    restart: always
    extra_hosts:
      - "thinkpad thinkpad.bigdata.net:host-gateway"
    ports:
      - "8088:8088"
      - "8025:8025"
      - "8032:8032"
      - "8050:8050"
    volumes:
      - /apps/hostpath:/apps/hostpath
    environment:
      SERVICE_PRECONDITION: "namenode:9000  namenode:50070  datanode:50075"
    env_file:
      - docker-hadoop-2.7.4/hadoop-2.7.4.env

  #
  nodemanager:
    image: brijeshdhaker/hadoop-nodemanager:2.7.4
    build:
      context: .
      dockerfile: docker-hadoop-2.7.4/nodemanager/Dockerfile
    container_name: nodemanager
    hostname: nodemanager
    restart: always
    extra_hosts:
      - "thinkpad thinkpad.bigdata.net:host-gateway"
    ports:
      - "8042:8042"
    volumes:
      - /apps/hostpath:/apps/hostpath
    environment:
      SERVICE_PRECONDITION: "namenode:9000  namenode:50070  datanode:50075 resourcemanager:8088"
    env_file:
      - docker-hadoop-2.7.4/hadoop-2.7.4.env

  #
  historyserver:
    image: brijeshdhaker/hadoop-historyserver:2.7.4
    build:
      context: .
      dockerfile: docker-hadoop-2.7.4/historyserver/Dockerfile
    container_name: historyserver
    hostname: historyserver
    restart: always
    extra_hosts:
      - "thinkpad thinkpad.bigdata.net:host-gateway"
    ports:
      - "8188:8188"
    environment:
      SERVICE_PRECONDITION: "namenode:9000  namenode:50070  datanode:50075 resourcemanager:8088"
    volumes:
      - /apps/hostpath:/apps/hostpath
    env_file:
      - docker-hadoop-2.7.4/hadoop-2.7.4.env

#
volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:

#
networks:
  default:
    external: true
    driver: bridge
    name: bigdata.net